-- Step 7.2D.0 - Catalogo base alimenti per Ricette.
--
-- Operazione esplicitamente richiesta: sostituisce gli alimenti esistenti con
-- un catalogo globale di base. Gli alimenti globali sono visibili a tutti; la
-- modifica e' consentita dal runtime solo all'amministratore di sistema.
--
-- La migration rimuove anche riferimenti generici (inviti/permessi) agli
-- alimenti precedenti e gli ingredienti ricetta che li referenziavano, poiche'
-- ricetta_ingredienti usa ON DELETE RESTRICT verso alimenti.

DELETE FROM inviti_risorsa WHERE tipo_risorsa = 'alimento';
DELETE FROM permessi_risorsa WHERE tipo_risorsa = 'alimento';
DELETE FROM ricetta_ingredienti;
DELETE FROM alimenti;

-- Un admin puo' assegnare categorie agli alimenti del catalogo globale.
DROP TRIGGER IF EXISTS trg_alimento_categoria_autorizzato_insert;
CREATE TRIGGER trg_alimento_categoria_autorizzato_insert
BEFORE INSERT ON alimento_categorie
WHEN NEW.assegnata_da_utente_id IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM alimenti a
    WHERE a.id = NEW.alimento_id
      AND a.proprietario_utente_id = NEW.assegnata_da_utente_id
)
AND NOT EXISTS (
    SELECT 1
    FROM permessi_risorsa pr
    WHERE pr.tipo_risorsa = 'alimento'
      AND pr.risorsa_id = NEW.alimento_id
      AND pr.utente_id = NEW.assegnata_da_utente_id
      AND pr.puo_modificare = 1
      AND EXISTS (
          SELECT 1
          FROM alimento_spazi asp
          JOIN membri_spazio ms ON ms.spazio_id = asp.spazio_id
          WHERE asp.alimento_id = NEW.alimento_id
            AND ms.utente_id = NEW.assegnata_da_utente_id
      )
)
AND NOT EXISTS (
    SELECT 1
    FROM alimenti a
    JOIN utenti u ON u.id = NEW.assegnata_da_utente_id
    WHERE a.id = NEW.alimento_id
      AND a.catalogo_globale = 1
      AND u.ruolo_sistema = 'admin'
      AND u.stato = 'attivo'
)
BEGIN
    SELECT RAISE(ABORT, 'utente non autorizzato a modificare categoria alimento');
END;

WITH seed(nome, nome_normalizzato, unita_codice, categoria_codice) AS (
    VALUES
    ('🥬 Zucchine', 'zucchine', 'g', 'verdura'),
    ('🥬 Zucchine trombetta', 'zucchine trombetta', 'g', 'verdura'),
    ('🥬 Melanzane', 'melanzane', 'g', 'verdura'),
    ('🥬 Peperoni rossi', 'peperoni rossi', 'g', 'verdura'),
    ('🥬 Peperoni gialli', 'peperoni gialli', 'g', 'verdura'),
    ('🥬 Peperoni verdi', 'peperoni verdi', 'g', 'verdura'),
    ('🥬 Pomodori', 'pomodori', 'g', 'verdura'),
    ('🥬 Pomodori ciliegini', 'pomodori ciliegini', 'g', 'verdura'),
    ('🥬 Pomodori datterini', 'pomodori datterini', 'g', 'verdura'),
    ('🥬 Pomodori San Marzano', 'pomodori san marzano', 'g', 'verdura'),
    ('🥬 Pomodori cuore di bue', 'pomodori cuore di bue', 'g', 'verdura'),
    ('🥬 Patate', 'patate', 'g', 'verdura'),
    ('🥬 Patate dolci', 'patate dolci', 'g', 'verdura'),
    ('🥬 Carote', 'carote', 'g', 'verdura'),
    ('🥬 Finocchi', 'finocchi', 'g', 'verdura'),
    ('🥬 Sedano', 'sedano', 'g', 'verdura'),
    ('🥬 Cetrioli', 'cetrioli', 'g', 'verdura'),
    ('🥬 Ravanelli', 'ravanelli', 'g', 'verdura'),
    ('🥬 Barbabietole', 'barbabietole', 'g', 'verdura'),
    ('🥬 Rape', 'rape', 'g', 'verdura'),
    ('🥬 Pastinaca', 'pastinaca', 'g', 'verdura'),
    ('🥬 Topinambur', 'topinambur', 'g', 'verdura'),
    ('🥬 Cavolfiore', 'cavolfiore', 'g', 'verdura'),
    ('🥬 Broccoli', 'broccoli', 'g', 'verdura'),
    ('🥬 Cavolo cappuccio', 'cavolo cappuccio', 'g', 'verdura'),
    ('🥬 Cavolo rosso', 'cavolo rosso', 'g', 'verdura'),
    ('🥬 Cavolo nero', 'cavolo nero', 'g', 'verdura'),
    ('🥬 Cavolo verza', 'cavolo verza', 'g', 'verdura'),
    ('🥬 Cavolini di Bruxelles', 'cavolini di bruxelles', 'g', 'verdura'),
    ('🥬 Bietole', 'bietole', 'g', 'verdura'),
    ('🥬 Spinaci', 'spinaci', 'g', 'verdura'),
    ('🥬 Lattuga', 'lattuga', 'g', 'verdura'),
    ('🥬 Insalata iceberg', 'insalata iceberg', 'g', 'verdura'),
    ('🥬 Rucola', 'rucola', 'g', 'verdura'),
    ('🥬 Radicchio', 'radicchio', 'g', 'verdura'),
    ('🥬 Scarola', 'scarola', 'g', 'verdura'),
    ('🥬 Catalogna', 'catalogna', 'g', 'verdura'),
    ('🥬 Cicoria', 'cicoria', 'g', 'verdura'),
    ('🥬 Porri', 'porri', 'g', 'verdura'),
    ('🥬 Cipolle bianche', 'cipolle bianche', 'g', 'verdura'),
    ('🥬 Cipolle rosse', 'cipolle rosse', 'g', 'verdura'),
    ('🥬 Cipolle dorate', 'cipolle dorate', 'g', 'verdura'),
    ('🥬 Cipollotti', 'cipollotti', 'g', 'verdura'),
    ('🥬 Scalogno', 'scalogno', 'g', 'verdura'),
    ('🥬 Aglio', 'aglio', 'g', 'verdura'),
    ('🥬 Asparagi', 'asparagi', 'g', 'verdura'),
    ('🥬 Carciofi', 'carciofi', 'g', 'verdura'),
    ('🥬 Fagiolini', 'fagiolini', 'g', 'verdura'),
    ('🥬 Piselli freschi', 'piselli freschi', 'g', 'verdura'),
    ('🥬 Fave fresche', 'fave fresche', 'g', 'verdura'),
    ('🥬 Zucca', 'zucca', 'g', 'verdura'),
    ('🥬 Zucca butternut', 'zucca butternut', 'g', 'verdura'),
    ('🥬 Mais dolce', 'mais dolce', 'g', 'verdura'),
    ('🥬 Funghi champignon', 'funghi champignon', 'g', 'verdura'),
    ('🥬 Funghi porcini', 'funghi porcini', 'g', 'verdura'),
    ('🥬 Funghi pleurotus', 'funghi pleurotus', 'g', 'verdura'),
    ('🥬 Funghi shiitake', 'funghi shiitake', 'g', 'verdura'),
    ('🥬 Germogli di soia', 'germogli di soia', 'g', 'verdura'),
    ('🥬 Germogli di bambù', 'germogli di bambù', 'g', 'verdura'),
    ('🥬 Avocado', 'avocado', 'g', 'verdura'),
    ('🥬 Olive verdi', 'olive verdi', 'g', 'verdura'),
    ('🥬 Olive nere', 'olive nere', 'g', 'verdura'),
    ('🍎 Mele', 'mele', 'g', 'frutta'),
    ('🍎 Mele Golden', 'mele golden', 'g', 'frutta'),
    ('🍎 Mele Granny Smith', 'mele granny smith', 'g', 'frutta'),
    ('🍎 Pere', 'pere', 'g', 'frutta'),
    ('🍎 Banane', 'banane', 'g', 'frutta'),
    ('🍎 Arance', 'arance', 'g', 'frutta'),
    ('🍎 Mandarini', 'mandarini', 'g', 'frutta'),
    ('🍎 Clementine', 'clementine', 'g', 'frutta'),
    ('🍎 Limoni', 'limoni', 'g', 'frutta'),
    ('🍎 Lime', 'lime', 'g', 'frutta'),
    ('🍎 Pompelmo', 'pompelmo', 'g', 'frutta'),
    ('🍎 Pesche', 'pesche', 'g', 'frutta'),
    ('🍎 Nettarine', 'nettarine', 'g', 'frutta'),
    ('🍎 Albicocche', 'albicocche', 'g', 'frutta'),
    ('🍎 Prugne', 'prugne', 'g', 'frutta'),
    ('🍎 Susine', 'susine', 'g', 'frutta'),
    ('🍎 Ciliegie', 'ciliegie', 'g', 'frutta'),
    ('🍎 Fragole', 'fragole', 'g', 'frutta'),
    ('🍎 Lamponi', 'lamponi', 'g', 'frutta'),
    ('🍎 Mirtilli', 'mirtilli', 'g', 'frutta'),
    ('🍎 More', 'more', 'g', 'frutta'),
    ('🍎 Ribes', 'ribes', 'g', 'frutta'),
    ('🍎 Uva bianca', 'uva bianca', 'g', 'frutta'),
    ('🍎 Uva nera', 'uva nera', 'g', 'frutta'),
    ('🍎 Kiwi', 'kiwi', 'g', 'frutta'),
    ('🍎 Ananas', 'ananas', 'g', 'frutta'),
    ('🍎 Mango', 'mango', 'g', 'frutta'),
    ('🍎 Papaya', 'papaya', 'g', 'frutta'),
    ('🍎 Melone', 'melone', 'g', 'frutta'),
    ('🍎 Anguria', 'anguria', 'g', 'frutta'),
    ('🍎 Cocco', 'cocco', 'g', 'frutta'),
    ('🍎 Melagrana', 'melagrana', 'g', 'frutta'),
    ('🍎 Fichi', 'fichi', 'g', 'frutta'),
    ('🍎 Cachi', 'cachi', 'g', 'frutta'),
    ('🍎 Datteri', 'datteri', 'g', 'frutta'),
    ('🍎 Fichi secchi', 'fichi secchi', 'g', 'frutta'),
    ('🍎 Uvetta', 'uvetta', 'g', 'frutta'),
    ('🍎 Cranberry essiccati', 'cranberry essiccati', 'g', 'frutta'),
    ('🍎 Frutti di bosco', 'frutti di bosco', 'g', 'frutta'),
    ('🍎 Frutti di bosco surgelati', 'frutti di bosco surgelati', 'g', 'frutta'),
    ('🥩 Petto di pollo', 'petto di pollo', 'g', 'carne'),
    ('🥩 Cosce di pollo', 'cosce di pollo', 'g', 'carne'),
    ('🥩 Sovracosce di pollo', 'sovracosce di pollo', 'g', 'carne'),
    ('🥩 Ali di pollo', 'ali di pollo', 'g', 'carne'),
    ('🥩 Pollo intero', 'pollo intero', 'g', 'carne'),
    ('🥩 Fesa di tacchino', 'fesa di tacchino', 'g', 'carne'),
    ('🥩 Petto di tacchino', 'petto di tacchino', 'g', 'carne'),
    ('🥩 Cosce di tacchino', 'cosce di tacchino', 'g', 'carne'),
    ('🥩 Macinato di manzo', 'macinato di manzo', 'g', 'carne'),
    ('🥩 Macinato misto', 'macinato misto', 'g', 'carne'),
    ('🥩 Macinato di maiale', 'macinato di maiale', 'g', 'carne'),
    ('🥩 Bistecca di manzo', 'bistecca di manzo', 'g', 'carne'),
    ('🥩 Controfiletto di manzo', 'controfiletto di manzo', 'g', 'carne'),
    ('🥩 Filetto di manzo', 'filetto di manzo', 'g', 'carne'),
    ('🥩 Roast beef', 'roast beef', 'g', 'carne'),
    ('🥩 Spezzatino di manzo', 'spezzatino di manzo', 'g', 'carne'),
    ('🥩 Costine di manzo', 'costine di manzo', 'g', 'carne'),
    ('🥩 Hamburger di manzo', 'hamburger di manzo', 'g', 'carne'),
    ('🥩 Vitello', 'vitello', 'g', 'carne'),
    ('🥩 Fettine di vitello', 'fettine di vitello', 'g', 'carne'),
    ('🥩 Ossobuco', 'ossobuco', 'g', 'carne'),
    ('🥩 Maiale', 'maiale', 'g', 'carne'),
    ('🥩 Lonza di maiale', 'lonza di maiale', 'g', 'carne'),
    ('🥩 Arista di maiale', 'arista di maiale', 'g', 'carne'),
    ('🥩 Filetto di maiale', 'filetto di maiale', 'g', 'carne'),
    ('🥩 Costine di maiale', 'costine di maiale', 'g', 'carne'),
    ('🥩 Braciole di maiale', 'braciole di maiale', 'g', 'carne'),
    ('🥩 Coppa di maiale', 'coppa di maiale', 'g', 'carne'),
    ('🥩 Pancetta', 'pancetta', 'g', 'carne'),
    ('🥩 Guanciale', 'guanciale', 'g', 'carne'),
    ('🥩 Salsiccia', 'salsiccia', 'g', 'carne'),
    ('🥩 Salamella', 'salamella', 'g', 'carne'),
    ('🥩 Prosciutto crudo', 'prosciutto crudo', 'g', 'carne'),
    ('🥩 Prosciutto cotto', 'prosciutto cotto', 'g', 'carne'),
    ('🥩 Speck', 'speck', 'g', 'carne'),
    ('🥩 Bresaola', 'bresaola', 'g', 'carne'),
    ('🥩 Mortadella', 'mortadella', 'g', 'carne'),
    ('🥩 Salame', 'salame', 'g', 'carne'),
    ('🥩 Würstel', 'würstel', 'g', 'carne'),
    ('🥩 Coniglio', 'coniglio', 'g', 'carne'),
    ('🥩 Agnello', 'agnello', 'g', 'carne'),
    ('🥩 Costolette di agnello', 'costolette di agnello', 'g', 'carne'),
    ('🥩 Anatra', 'anatra', 'g', 'carne'),
    ('🥩 Petto di anatra', 'petto di anatra', 'g', 'carne'),
    ('🥩 Cinghiale', 'cinghiale', 'g', 'carne'),
    ('🐟 Salmone', 'salmone', 'g', 'pesce'),
    ('🐟 Tonno fresco', 'tonno fresco', 'g', 'pesce'),
    ('🐟 Tonno in scatola', 'tonno in scatola', 'g', 'pesce'),
    ('🐟 Merluzzo', 'merluzzo', 'g', 'pesce'),
    ('🐟 Nasello', 'nasello', 'g', 'pesce'),
    ('🐟 Orata', 'orata', 'g', 'pesce'),
    ('🐟 Branzino', 'branzino', 'g', 'pesce'),
    ('🐟 Sogliola', 'sogliola', 'g', 'pesce'),
    ('🐟 Trota', 'trota', 'g', 'pesce'),
    ('🐟 Pesce spada', 'pesce spada', 'g', 'pesce'),
    ('🐟 Sgombro', 'sgombro', 'g', 'pesce'),
    ('🐟 Sardine', 'sardine', 'g', 'pesce'),
    ('🐟 Acciughe', 'acciughe', 'g', 'pesce'),
    ('🐟 Alici', 'alici', 'g', 'pesce'),
    ('🐟 Gamberi', 'gamberi', 'g', 'pesce'),
    ('🐟 Gamberetti', 'gamberetti', 'g', 'pesce'),
    ('🐟 Mazzancolle', 'mazzancolle', 'g', 'pesce'),
    ('🐟 Scampi', 'scampi', 'g', 'pesce'),
    ('🐟 Calamari', 'calamari', 'g', 'pesce'),
    ('🐟 Totani', 'totani', 'g', 'pesce'),
    ('🐟 Polpo', 'polpo', 'g', 'pesce'),
    ('🐟 Seppie', 'seppie', 'g', 'pesce'),
    ('🐟 Cozze', 'cozze', 'g', 'pesce'),
    ('🐟 Vongole', 'vongole', 'g', 'pesce'),
    ('🐟 Capasanta', 'capasanta', 'g', 'pesce'),
    ('🐟 Granchio', 'granchio', 'g', 'pesce'),
    ('🐟 Surimi', 'surimi', 'g', 'pesce'),
    ('🥛 Latte intero', 'latte intero', 'g', 'latticini'),
    ('🥛 Latte parzialmente scremato', 'latte parzialmente scremato', 'g', 'latticini'),
    ('🥛 Latte scremato', 'latte scremato', 'g', 'latticini'),
    ('🥛 Panna fresca', 'panna fresca', 'g', 'latticini'),
    ('🥛 Panna da cucina', 'panna da cucina', 'g', 'latticini'),
    ('🥛 Burro', 'burro', 'g', 'latticini'),
    ('🥛 Burro chiarificato', 'burro chiarificato', 'g', 'latticini'),
    ('🥛 Yogurt bianco', 'yogurt bianco', 'g', 'latticini'),
    ('🥛 Yogurt greco', 'yogurt greco', 'g', 'latticini'),
    ('🥛 Mascarpone', 'mascarpone', 'g', 'latticini'),
    ('🥛 Ricotta', 'ricotta', 'g', 'latticini'),
    ('🥛 Mozzarella', 'mozzarella', 'g', 'latticini'),
    ('🥛 Mozzarella di bufala', 'mozzarella di bufala', 'g', 'latticini'),
    ('🥛 Burrata', 'burrata', 'g', 'latticini'),
    ('🥛 Stracciatella', 'stracciatella', 'g', 'latticini'),
    ('🥛 Scamorza', 'scamorza', 'g', 'latticini'),
    ('🥛 Provola', 'provola', 'g', 'latticini'),
    ('🥛 Provolone', 'provolone', 'g', 'latticini'),
    ('🥛 Parmigiano Reggiano', 'parmigiano reggiano', 'g', 'latticini'),
    ('🥛 Grana Padano', 'grana padano', 'g', 'latticini'),
    ('🥛 Pecorino romano', 'pecorino romano', 'g', 'latticini'),
    ('🥛 Pecorino sardo', 'pecorino sardo', 'g', 'latticini'),
    ('🥛 Gorgonzola', 'gorgonzola', 'g', 'latticini'),
    ('🥛 Taleggio', 'taleggio', 'g', 'latticini'),
    ('🥛 Fontina', 'fontina', 'g', 'latticini'),
    ('🥛 Asiago', 'asiago', 'g', 'latticini'),
    ('🥛 Emmental', 'emmental', 'g', 'latticini'),
    ('🥛 Gruyère', 'gruyère', 'g', 'latticini'),
    ('🥛 Cheddar', 'cheddar', 'g', 'latticini'),
    ('🥛 Edam', 'edam', 'g', 'latticini'),
    ('🥛 Gouda', 'gouda', 'g', 'latticini'),
    ('🥛 Feta', 'feta', 'g', 'latticini'),
    ('🥛 Crescenza', 'crescenza', 'g', 'latticini'),
    ('🥛 Robiola', 'robiola', 'g', 'latticini'),
    ('🥛 Caprino', 'caprino', 'g', 'latticini'),
    ('🥛 Formaggio spalmabile', 'formaggio spalmabile', 'g', 'latticini'),
    ('🥚 Uova', 'uova', 'pz', 'uova'),
    ('🥚 Albumi', 'albumi', 'pz', 'uova'),
    ('🥚 Tuorli', 'tuorli', 'pz', 'uova'),
    ('🌾 Riso', 'riso', 'g', 'cereali'),
    ('🌾 Riso basmati', 'riso basmati', 'g', 'cereali'),
    ('🌾 Riso jasmine', 'riso jasmine', 'g', 'cereali'),
    ('🌾 Riso arborio', 'riso arborio', 'g', 'cereali'),
    ('🌾 Riso carnaroli', 'riso carnaroli', 'g', 'cereali'),
    ('🌾 Riso venere', 'riso venere', 'g', 'cereali'),
    ('🌾 Riso integrale', 'riso integrale', 'g', 'cereali'),
    ('🌾 Pasta', 'pasta', 'g', 'cereali'),
    ('🌾 Spaghetti', 'spaghetti', 'g', 'cereali'),
    ('🌾 Linguine', 'linguine', 'g', 'cereali'),
    ('🌾 Bucatini', 'bucatini', 'g', 'cereali'),
    ('🌾 Penne', 'penne', 'g', 'cereali'),
    ('🌾 Rigatoni', 'rigatoni', 'g', 'cereali'),
    ('🌾 Fusilli', 'fusilli', 'g', 'cereali'),
    ('🌾 Farfalle', 'farfalle', 'g', 'cereali'),
    ('🌾 Paccheri', 'paccheri', 'g', 'cereali'),
    ('🌾 Orecchiette', 'orecchiette', 'g', 'cereali'),
    ('🌾 Tagliatelle', 'tagliatelle', 'g', 'cereali'),
    ('🌾 Pappardelle', 'pappardelle', 'g', 'cereali'),
    ('🌾 Lasagne', 'lasagne', 'g', 'cereali'),
    ('🌾 Gnocchi di patate', 'gnocchi di patate', 'g', 'cereali'),
    ('🌾 Tortellini', 'tortellini', 'g', 'cereali'),
    ('🌾 Ravioli', 'ravioli', 'g', 'cereali'),
    ('🌾 Cous cous', 'cous cous', 'g', 'cereali'),
    ('🌾 Bulgur', 'bulgur', 'g', 'cereali'),
    ('🌾 Quinoa', 'quinoa', 'g', 'cereali'),
    ('🌾 Farro', 'farro', 'g', 'cereali'),
    ('🌾 Orzo perlato', 'orzo perlato', 'g', 'cereali'),
    ('🌾 Avena', 'avena', 'g', 'cereali'),
    ('🌾 Fiocchi di avena', 'fiocchi di avena', 'g', 'cereali'),
    ('🌾 Semolino', 'semolino', 'g', 'cereali'),
    ('🌾 Polenta', 'polenta', 'g', 'cereali'),
    ('🌾 Farina 00', 'farina 00', 'g', 'cereali'),
    ('🌾 Farina 0', 'farina 0', 'g', 'cereali'),
    ('🌾 Farina Manitoba', 'farina manitoba', 'g', 'cereali'),
    ('🌾 Farina integrale', 'farina integrale', 'g', 'cereali'),
    ('🌾 Farina di semola', 'farina di semola', 'g', 'cereali'),
    ('🌾 Farina di mais', 'farina di mais', 'g', 'cereali'),
    ('🌾 Farina di riso', 'farina di riso', 'g', 'cereali'),
    ('🌾 Farina di avena', 'farina di avena', 'g', 'cereali'),
    ('🌾 Farina di ceci', 'farina di ceci', 'g', 'cereali'),
    ('🌾 Amido di mais', 'amido di mais', 'g', 'cereali'),
    ('🌾 Fecola di patate', 'fecola di patate', 'g', 'cereali'),
    ('🌾 Pane', 'pane', 'g', 'cereali'),
    ('🌾 Pane bianco', 'pane bianco', 'g', 'cereali'),
    ('🌾 Pane integrale', 'pane integrale', 'g', 'cereali'),
    ('🌾 Pane in cassetta', 'pane in cassetta', 'g', 'cereali'),
    ('🌾 Pan brioche', 'pan brioche', 'g', 'cereali'),
    ('🌾 Baguette', 'baguette', 'g', 'cereali'),
    ('🌾 Ciabatta', 'ciabatta', 'g', 'cereali'),
    ('🌾 Piadina', 'piadina', 'g', 'cereali'),
    ('🌾 Tortilla di grano', 'tortilla di grano', 'g', 'cereali'),
    ('🌾 Tortilla di mais', 'tortilla di mais', 'g', 'cereali'),
    ('🌾 Pangrattato', 'pangrattato', 'g', 'cereali'),
    ('🌾 Cracker', 'cracker', 'g', 'cereali'),
    ('🌾 Grissini', 'grissini', 'g', 'cereali'),
    ('🌾 Fette biscottate', 'fette biscottate', 'g', 'cereali'),
    ('🌾 Corn flakes', 'corn flakes', 'g', 'cereali'),
    ('🫘 Fagioli borlotti', 'fagioli borlotti', 'g', 'legumi'),
    ('🫘 Fagioli cannellini', 'fagioli cannellini', 'g', 'legumi'),
    ('🫘 Fagioli neri', 'fagioli neri', 'g', 'legumi'),
    ('🫘 Fagioli rossi', 'fagioli rossi', 'g', 'legumi'),
    ('🫘 Fagioli azuki', 'fagioli azuki', 'g', 'legumi'),
    ('🫘 Ceci', 'ceci', 'g', 'legumi'),
    ('🫘 Lenticchie', 'lenticchie', 'g', 'legumi'),
    ('🫘 Lenticchie rosse', 'lenticchie rosse', 'g', 'legumi'),
    ('🫘 Piselli secchi', 'piselli secchi', 'g', 'legumi'),
    ('🫘 Fave secche', 'fave secche', 'g', 'legumi'),
    ('🫘 Soia', 'soia', 'g', 'legumi'),
    ('🫘 Edamame', 'edamame', 'g', 'legumi'),
    ('🫘 Tofu', 'tofu', 'g', 'legumi'),
    ('🫘 Tempeh', 'tempeh', 'g', 'legumi'),
    ('🧂 Sale fino', 'sale fino', 'g', 'condimenti'),
    ('🧂 Sale grosso', 'sale grosso', 'g', 'condimenti'),
    ('🧂 Pepe nero', 'pepe nero', 'g', 'condimenti'),
    ('🧂 Pepe bianco', 'pepe bianco', 'g', 'condimenti'),
    ('🧂 Pepe rosa', 'pepe rosa', 'g', 'condimenti'),
    ('🧂 Paprika dolce', 'paprika dolce', 'g', 'condimenti'),
    ('🧂 Paprika affumicata', 'paprika affumicata', 'g', 'condimenti'),
    ('🧂 Peperoncino', 'peperoncino', 'g', 'condimenti'),
    ('🧂 Curry', 'curry', 'g', 'condimenti'),
    ('🧂 Curcuma', 'curcuma', 'g', 'condimenti'),
    ('🧂 Cumino', 'cumino', 'g', 'condimenti'),
    ('🧂 Coriandolo in polvere', 'coriandolo in polvere', 'g', 'condimenti'),
    ('🧂 Cannella', 'cannella', 'g', 'condimenti'),
    ('🧂 Noce moscata', 'noce moscata', 'g', 'condimenti'),
    ('🧂 Zenzero in polvere', 'zenzero in polvere', 'g', 'condimenti'),
    ('🧂 Aglio in polvere', 'aglio in polvere', 'g', 'condimenti'),
    ('🧂 Cipolla in polvere', 'cipolla in polvere', 'g', 'condimenti'),
    ('🧂 Origano', 'origano', 'g', 'condimenti'),
    ('🧂 Basilico', 'basilico', 'g', 'condimenti'),
    ('🧂 Prezzemolo', 'prezzemolo', 'g', 'condimenti'),
    ('🧂 Rosmarino', 'rosmarino', 'g', 'condimenti'),
    ('🧂 Salvia', 'salvia', 'g', 'condimenti'),
    ('🧂 Timo', 'timo', 'g', 'condimenti'),
    ('🧂 Maggiorana', 'maggiorana', 'g', 'condimenti'),
    ('🧂 Erba cipollina', 'erba cipollina', 'g', 'condimenti'),
    ('🧂 Aneto', 'aneto', 'g', 'condimenti'),
    ('🧂 Menta', 'menta', 'g', 'condimenti'),
    ('🧂 Alloro', 'alloro', 'g', 'condimenti'),
    ('🧂 Semi di sesamo', 'semi di sesamo', 'g', 'condimenti'),
    ('🧂 Semi di papavero', 'semi di papavero', 'g', 'condimenti'),
    ('🧂 Semi di lino', 'semi di lino', 'g', 'condimenti'),
    ('🧂 Semi di chia', 'semi di chia', 'g', 'condimenti'),
    ('🧂 Semi di zucca', 'semi di zucca', 'g', 'condimenti'),
    ('🧂 Semi di girasole', 'semi di girasole', 'g', 'condimenti'),
    ('🧂 Pinoli', 'pinoli', 'g', 'condimenti'),
    ('🧂 Mandorle', 'mandorle', 'g', 'condimenti'),
    ('🧂 Nocciole', 'nocciole', 'g', 'condimenti'),
    ('🧂 Noci', 'noci', 'g', 'condimenti'),
    ('🧂 Pistacchi', 'pistacchi', 'g', 'condimenti'),
    ('🧂 Anacardi', 'anacardi', 'g', 'condimenti'),
    ('🧂 Arachidi', 'arachidi', 'g', 'condimenti'),
    ('🧂 Olio extravergine di oliva', 'olio extravergine di oliva', 'ml', 'condimenti'),
    ('🧂 Olio di oliva', 'olio di oliva', 'ml', 'condimenti'),
    ('🧂 Olio di semi di girasole', 'olio di semi di girasole', 'ml', 'condimenti'),
    ('🧂 Olio di arachidi', 'olio di arachidi', 'ml', 'condimenti'),
    ('🧂 Olio di mais', 'olio di mais', 'ml', 'condimenti'),
    ('🧂 Olio di sesamo', 'olio di sesamo', 'ml', 'condimenti'),
    ('🧂 Aceto di vino bianco', 'aceto di vino bianco', 'ml', 'condimenti'),
    ('🧂 Aceto di vino rosso', 'aceto di vino rosso', 'ml', 'condimenti'),
    ('🧂 Aceto balsamico', 'aceto balsamico', 'ml', 'condimenti'),
    ('🧂 Aceto di mele', 'aceto di mele', 'ml', 'condimenti'),
    ('🧂 Salsa di soia', 'salsa di soia', 'ml', 'condimenti'),
    ('🧂 Salsa teriyaki', 'salsa teriyaki', 'ml', 'condimenti'),
    ('🧂 Salsa Worcestershire', 'salsa worcestershire', 'ml', 'condimenti'),
    ('🧂 Ketchup', 'ketchup', 'ml', 'condimenti'),
    ('🧂 Maionese', 'maionese', 'ml', 'condimenti'),
    ('🧂 Senape', 'senape', 'ml', 'condimenti'),
    ('🧂 Senape di Digione', 'senape di digione', 'ml', 'condimenti'),
    ('🧂 Salsa barbecue', 'salsa barbecue', 'ml', 'condimenti'),
    ('🧂 Tabasco', 'tabasco', 'ml', 'condimenti'),
    ('🧂 Pesto', 'pesto', 'ml', 'condimenti'),
    ('🧂 Passata di pomodoro', 'passata di pomodoro', 'ml', 'condimenti'),
    ('🧂 Polpa di pomodoro', 'polpa di pomodoro', 'ml', 'condimenti'),
    ('🧂 Concentrato di pomodoro', 'concentrato di pomodoro', 'g', 'condimenti'),
    ('🧂 Pelati', 'pelati', 'g', 'condimenti'),
    ('🧂 Brodo vegetale', 'brodo vegetale', 'ml', 'condimenti'),
    ('🧂 Brodo di carne', 'brodo di carne', 'ml', 'condimenti'),
    ('🧂 Dado vegetale', 'dado vegetale', 'g', 'condimenti'),
    ('🧂 Dado di carne', 'dado di carne', 'g', 'condimenti'),
    ('🧂 Capperi', 'capperi', 'g', 'condimenti'),
    ('🧂 Cetriolini sottaceto', 'cetriolini sottaceto', 'g', 'condimenti'),
    ('🧂 Miele', 'miele', 'ml', 'condimenti'),
    ('🧂 Sciroppo d’acero', 'sciroppo d’acero', 'ml', 'condimenti'),
    ('🥤 Acqua', 'acqua', 'ml', 'bevande'),
    ('🥤 Acqua frizzante', 'acqua frizzante', 'ml', 'bevande'),
    ('🥤 Latte di soia', 'latte di soia', 'ml', 'bevande'),
    ('🥤 Latte di mandorla', 'latte di mandorla', 'ml', 'bevande'),
    ('🥤 Latte di avena', 'latte di avena', 'ml', 'bevande'),
    ('🥤 Latte di cocco', 'latte di cocco', 'ml', 'bevande'),
    ('🥤 Succo d’arancia', 'succo d’arancia', 'ml', 'bevande'),
    ('🥤 Succo di mela', 'succo di mela', 'ml', 'bevande'),
    ('🥤 Succo di ananas', 'succo di ananas', 'ml', 'bevande'),
    ('🥤 Succo di limone', 'succo di limone', 'ml', 'bevande'),
    ('🥤 Succo di lime', 'succo di lime', 'ml', 'bevande'),
    ('🥤 Caffè', 'caffè', 'ml', 'bevande'),
    ('🥤 Caffè espresso', 'caffè espresso', 'ml', 'bevande'),
    ('🥤 Caffè solubile', 'caffè solubile', 'ml', 'bevande'),
    ('🥤 Tè nero', 'tè nero', 'ml', 'bevande'),
    ('🥤 Tè verde', 'tè verde', 'ml', 'bevande'),
    ('🥤 Tè matcha', 'tè matcha', 'ml', 'bevande'),
    ('🥤 Camomilla', 'camomilla', 'ml', 'bevande'),
    ('🥤 Birra analcolica', 'birra analcolica', 'ml', 'bevande'),
    ('🥤 Acqua tonica', 'acqua tonica', 'ml', 'bevande'),
    ('🍰 Zucchero semolato', 'zucchero semolato', 'g', 'dolci'),
    ('🍰 Zucchero di canna', 'zucchero di canna', 'g', 'dolci'),
    ('🍰 Zucchero a velo', 'zucchero a velo', 'g', 'dolci'),
    ('🍰 Cacao amaro', 'cacao amaro', 'g', 'dolci'),
    ('🍰 Cacao zuccherato', 'cacao zuccherato', 'g', 'dolci'),
    ('🍰 Cioccolato fondente', 'cioccolato fondente', 'g', 'dolci'),
    ('🍰 Cioccolato al latte', 'cioccolato al latte', 'g', 'dolci'),
    ('🍰 Cioccolato bianco', 'cioccolato bianco', 'g', 'dolci'),
    ('🍰 Gocce di cioccolato', 'gocce di cioccolato', 'g', 'dolci'),
    ('🍰 Nutella', 'nutella', 'g', 'dolci'),
    ('🍰 Crema di nocciole', 'crema di nocciole', 'g', 'dolci'),
    ('🍰 Marmellata', 'marmellata', 'g', 'dolci'),
    ('🍰 Confettura', 'confettura', 'g', 'dolci'),
    ('🍰 Gelatina alimentare', 'gelatina alimentare', 'g', 'dolci'),
    ('🍰 Lievito per dolci', 'lievito per dolci', 'g', 'dolci'),
    ('🍰 Bicarbonato', 'bicarbonato', 'g', 'dolci'),
    ('🍰 Vanillina', 'vanillina', 'g', 'dolci'),
    ('🍰 Estratto di vaniglia', 'estratto di vaniglia', 'g', 'dolci'),
    ('🍰 Baccello di vaniglia', 'baccello di vaniglia', 'g', 'dolci'),
    ('🍰 Savoiardi', 'savoiardi', 'g', 'dolci'),
    ('🍰 Biscotti secchi', 'biscotti secchi', 'g', 'dolci'),
    ('🍰 Amaretti', 'amaretti', 'g', 'dolci'),
    ('🍰 Pan di Spagna', 'pan di spagna', 'g', 'dolci'),
    ('🍰 Marshmallow', 'marshmallow', 'g', 'dolci'),
    ('🍰 Caramello', 'caramello', 'g', 'dolci'),
    ('🍰 Codette di zucchero', 'codette di zucchero', 'g', 'dolci'),
    ('🏷️ Lievito di birra fresco', 'lievito di birra fresco', 'g', 'altro'),
    ('🏷️ Lievito di birra secco', 'lievito di birra secco', 'g', 'altro'),
    ('🏷️ Lievito madre', 'lievito madre', 'g', 'altro'),
    ('🏷️ Agar agar', 'agar agar', 'g', 'altro'),
    ('🏷️ Colla di pesce', 'colla di pesce', 'g', 'altro'),
    ('🏷️ Miso', 'miso', 'g', 'altro'),
    ('🏷️ Tahina', 'tahina', 'g', 'altro'),
    ('🏷️ Hummus', 'hummus', 'g', 'altro'),
    ('🏷️ Latte di cocco da cucina', 'latte di cocco da cucina', 'g', 'altro'),
    ('🏷️ Pasta sfoglia', 'pasta sfoglia', 'g', 'altro'),
    ('🏷️ Pasta brisée', 'pasta brisée', 'g', 'altro'),
    ('🏷️ Pasta fillo', 'pasta fillo', 'g', 'altro'),
    ('🏷️ Base per pizza', 'base per pizza', 'g', 'altro'),
    ('🏷️ Seitan', 'seitan', 'g', 'altro')
)
INSERT INTO alimenti (
    spazio_id, nome, nome_normalizzato, descrizione, unita_predefinita_id,
    creato_da_utente_id, proprietario_utente_id, catalogo_globale, archiviato
)
SELECT
    NULL,
    seed.nome,
    seed.nome_normalizzato,
    'Alimento base del catalogo globale',
    um.id,
    NULL,
    NULL,
    1,
    0
FROM seed
JOIN unita_misura um ON um.codice = seed.unita_codice;

-- Il trigger di default assegna Altro: sostituiamo con la categoria prevista.
DELETE FROM alimento_categorie
WHERE alimento_id IN (SELECT id FROM alimenti WHERE catalogo_globale = 1);

WITH seed(nome, nome_normalizzato, unita_codice, categoria_codice) AS (
    VALUES
    ('🥬 Zucchine', 'zucchine', 'g', 'verdura'),
    ('🥬 Zucchine trombetta', 'zucchine trombetta', 'g', 'verdura'),
    ('🥬 Melanzane', 'melanzane', 'g', 'verdura'),
    ('🥬 Peperoni rossi', 'peperoni rossi', 'g', 'verdura'),
    ('🥬 Peperoni gialli', 'peperoni gialli', 'g', 'verdura'),
    ('🥬 Peperoni verdi', 'peperoni verdi', 'g', 'verdura'),
    ('🥬 Pomodori', 'pomodori', 'g', 'verdura'),
    ('🥬 Pomodori ciliegini', 'pomodori ciliegini', 'g', 'verdura'),
    ('🥬 Pomodori datterini', 'pomodori datterini', 'g', 'verdura'),
    ('🥬 Pomodori San Marzano', 'pomodori san marzano', 'g', 'verdura'),
    ('🥬 Pomodori cuore di bue', 'pomodori cuore di bue', 'g', 'verdura'),
    ('🥬 Patate', 'patate', 'g', 'verdura'),
    ('🥬 Patate dolci', 'patate dolci', 'g', 'verdura'),
    ('🥬 Carote', 'carote', 'g', 'verdura'),
    ('🥬 Finocchi', 'finocchi', 'g', 'verdura'),
    ('🥬 Sedano', 'sedano', 'g', 'verdura'),
    ('🥬 Cetrioli', 'cetrioli', 'g', 'verdura'),
    ('🥬 Ravanelli', 'ravanelli', 'g', 'verdura'),
    ('🥬 Barbabietole', 'barbabietole', 'g', 'verdura'),
    ('🥬 Rape', 'rape', 'g', 'verdura'),
    ('🥬 Pastinaca', 'pastinaca', 'g', 'verdura'),
    ('🥬 Topinambur', 'topinambur', 'g', 'verdura'),
    ('🥬 Cavolfiore', 'cavolfiore', 'g', 'verdura'),
    ('🥬 Broccoli', 'broccoli', 'g', 'verdura'),
    ('🥬 Cavolo cappuccio', 'cavolo cappuccio', 'g', 'verdura'),
    ('🥬 Cavolo rosso', 'cavolo rosso', 'g', 'verdura'),
    ('🥬 Cavolo nero', 'cavolo nero', 'g', 'verdura'),
    ('🥬 Cavolo verza', 'cavolo verza', 'g', 'verdura'),
    ('🥬 Cavolini di Bruxelles', 'cavolini di bruxelles', 'g', 'verdura'),
    ('🥬 Bietole', 'bietole', 'g', 'verdura'),
    ('🥬 Spinaci', 'spinaci', 'g', 'verdura'),
    ('🥬 Lattuga', 'lattuga', 'g', 'verdura'),
    ('🥬 Insalata iceberg', 'insalata iceberg', 'g', 'verdura'),
    ('🥬 Rucola', 'rucola', 'g', 'verdura'),
    ('🥬 Radicchio', 'radicchio', 'g', 'verdura'),
    ('🥬 Scarola', 'scarola', 'g', 'verdura'),
    ('🥬 Catalogna', 'catalogna', 'g', 'verdura'),
    ('🥬 Cicoria', 'cicoria', 'g', 'verdura'),
    ('🥬 Porri', 'porri', 'g', 'verdura'),
    ('🥬 Cipolle bianche', 'cipolle bianche', 'g', 'verdura'),
    ('🥬 Cipolle rosse', 'cipolle rosse', 'g', 'verdura'),
    ('🥬 Cipolle dorate', 'cipolle dorate', 'g', 'verdura'),
    ('🥬 Cipollotti', 'cipollotti', 'g', 'verdura'),
    ('🥬 Scalogno', 'scalogno', 'g', 'verdura'),
    ('🥬 Aglio', 'aglio', 'g', 'verdura'),
    ('🥬 Asparagi', 'asparagi', 'g', 'verdura'),
    ('🥬 Carciofi', 'carciofi', 'g', 'verdura'),
    ('🥬 Fagiolini', 'fagiolini', 'g', 'verdura'),
    ('🥬 Piselli freschi', 'piselli freschi', 'g', 'verdura'),
    ('🥬 Fave fresche', 'fave fresche', 'g', 'verdura'),
    ('🥬 Zucca', 'zucca', 'g', 'verdura'),
    ('🥬 Zucca butternut', 'zucca butternut', 'g', 'verdura'),
    ('🥬 Mais dolce', 'mais dolce', 'g', 'verdura'),
    ('🥬 Funghi champignon', 'funghi champignon', 'g', 'verdura'),
    ('🥬 Funghi porcini', 'funghi porcini', 'g', 'verdura'),
    ('🥬 Funghi pleurotus', 'funghi pleurotus', 'g', 'verdura'),
    ('🥬 Funghi shiitake', 'funghi shiitake', 'g', 'verdura'),
    ('🥬 Germogli di soia', 'germogli di soia', 'g', 'verdura'),
    ('🥬 Germogli di bambù', 'germogli di bambù', 'g', 'verdura'),
    ('🥬 Avocado', 'avocado', 'g', 'verdura'),
    ('🥬 Olive verdi', 'olive verdi', 'g', 'verdura'),
    ('🥬 Olive nere', 'olive nere', 'g', 'verdura'),
    ('🍎 Mele', 'mele', 'g', 'frutta'),
    ('🍎 Mele Golden', 'mele golden', 'g', 'frutta'),
    ('🍎 Mele Granny Smith', 'mele granny smith', 'g', 'frutta'),
    ('🍎 Pere', 'pere', 'g', 'frutta'),
    ('🍎 Banane', 'banane', 'g', 'frutta'),
    ('🍎 Arance', 'arance', 'g', 'frutta'),
    ('🍎 Mandarini', 'mandarini', 'g', 'frutta'),
    ('🍎 Clementine', 'clementine', 'g', 'frutta'),
    ('🍎 Limoni', 'limoni', 'g', 'frutta'),
    ('🍎 Lime', 'lime', 'g', 'frutta'),
    ('🍎 Pompelmo', 'pompelmo', 'g', 'frutta'),
    ('🍎 Pesche', 'pesche', 'g', 'frutta'),
    ('🍎 Nettarine', 'nettarine', 'g', 'frutta'),
    ('🍎 Albicocche', 'albicocche', 'g', 'frutta'),
    ('🍎 Prugne', 'prugne', 'g', 'frutta'),
    ('🍎 Susine', 'susine', 'g', 'frutta'),
    ('🍎 Ciliegie', 'ciliegie', 'g', 'frutta'),
    ('🍎 Fragole', 'fragole', 'g', 'frutta'),
    ('🍎 Lamponi', 'lamponi', 'g', 'frutta'),
    ('🍎 Mirtilli', 'mirtilli', 'g', 'frutta'),
    ('🍎 More', 'more', 'g', 'frutta'),
    ('🍎 Ribes', 'ribes', 'g', 'frutta'),
    ('🍎 Uva bianca', 'uva bianca', 'g', 'frutta'),
    ('🍎 Uva nera', 'uva nera', 'g', 'frutta'),
    ('🍎 Kiwi', 'kiwi', 'g', 'frutta'),
    ('🍎 Ananas', 'ananas', 'g', 'frutta'),
    ('🍎 Mango', 'mango', 'g', 'frutta'),
    ('🍎 Papaya', 'papaya', 'g', 'frutta'),
    ('🍎 Melone', 'melone', 'g', 'frutta'),
    ('🍎 Anguria', 'anguria', 'g', 'frutta'),
    ('🍎 Cocco', 'cocco', 'g', 'frutta'),
    ('🍎 Melagrana', 'melagrana', 'g', 'frutta'),
    ('🍎 Fichi', 'fichi', 'g', 'frutta'),
    ('🍎 Cachi', 'cachi', 'g', 'frutta'),
    ('🍎 Datteri', 'datteri', 'g', 'frutta'),
    ('🍎 Fichi secchi', 'fichi secchi', 'g', 'frutta'),
    ('🍎 Uvetta', 'uvetta', 'g', 'frutta'),
    ('🍎 Cranberry essiccati', 'cranberry essiccati', 'g', 'frutta'),
    ('🍎 Frutti di bosco', 'frutti di bosco', 'g', 'frutta'),
    ('🍎 Frutti di bosco surgelati', 'frutti di bosco surgelati', 'g', 'frutta'),
    ('🥩 Petto di pollo', 'petto di pollo', 'g', 'carne'),
    ('🥩 Cosce di pollo', 'cosce di pollo', 'g', 'carne'),
    ('🥩 Sovracosce di pollo', 'sovracosce di pollo', 'g', 'carne'),
    ('🥩 Ali di pollo', 'ali di pollo', 'g', 'carne'),
    ('🥩 Pollo intero', 'pollo intero', 'g', 'carne'),
    ('🥩 Fesa di tacchino', 'fesa di tacchino', 'g', 'carne'),
    ('🥩 Petto di tacchino', 'petto di tacchino', 'g', 'carne'),
    ('🥩 Cosce di tacchino', 'cosce di tacchino', 'g', 'carne'),
    ('🥩 Macinato di manzo', 'macinato di manzo', 'g', 'carne'),
    ('🥩 Macinato misto', 'macinato misto', 'g', 'carne'),
    ('🥩 Macinato di maiale', 'macinato di maiale', 'g', 'carne'),
    ('🥩 Bistecca di manzo', 'bistecca di manzo', 'g', 'carne'),
    ('🥩 Controfiletto di manzo', 'controfiletto di manzo', 'g', 'carne'),
    ('🥩 Filetto di manzo', 'filetto di manzo', 'g', 'carne'),
    ('🥩 Roast beef', 'roast beef', 'g', 'carne'),
    ('🥩 Spezzatino di manzo', 'spezzatino di manzo', 'g', 'carne'),
    ('🥩 Costine di manzo', 'costine di manzo', 'g', 'carne'),
    ('🥩 Hamburger di manzo', 'hamburger di manzo', 'g', 'carne'),
    ('🥩 Vitello', 'vitello', 'g', 'carne'),
    ('🥩 Fettine di vitello', 'fettine di vitello', 'g', 'carne'),
    ('🥩 Ossobuco', 'ossobuco', 'g', 'carne'),
    ('🥩 Maiale', 'maiale', 'g', 'carne'),
    ('🥩 Lonza di maiale', 'lonza di maiale', 'g', 'carne'),
    ('🥩 Arista di maiale', 'arista di maiale', 'g', 'carne'),
    ('🥩 Filetto di maiale', 'filetto di maiale', 'g', 'carne'),
    ('🥩 Costine di maiale', 'costine di maiale', 'g', 'carne'),
    ('🥩 Braciole di maiale', 'braciole di maiale', 'g', 'carne'),
    ('🥩 Coppa di maiale', 'coppa di maiale', 'g', 'carne'),
    ('🥩 Pancetta', 'pancetta', 'g', 'carne'),
    ('🥩 Guanciale', 'guanciale', 'g', 'carne'),
    ('🥩 Salsiccia', 'salsiccia', 'g', 'carne'),
    ('🥩 Salamella', 'salamella', 'g', 'carne'),
    ('🥩 Prosciutto crudo', 'prosciutto crudo', 'g', 'carne'),
    ('🥩 Prosciutto cotto', 'prosciutto cotto', 'g', 'carne'),
    ('🥩 Speck', 'speck', 'g', 'carne'),
    ('🥩 Bresaola', 'bresaola', 'g', 'carne'),
    ('🥩 Mortadella', 'mortadella', 'g', 'carne'),
    ('🥩 Salame', 'salame', 'g', 'carne'),
    ('🥩 Würstel', 'würstel', 'g', 'carne'),
    ('🥩 Coniglio', 'coniglio', 'g', 'carne'),
    ('🥩 Agnello', 'agnello', 'g', 'carne'),
    ('🥩 Costolette di agnello', 'costolette di agnello', 'g', 'carne'),
    ('🥩 Anatra', 'anatra', 'g', 'carne'),
    ('🥩 Petto di anatra', 'petto di anatra', 'g', 'carne'),
    ('🥩 Cinghiale', 'cinghiale', 'g', 'carne'),
    ('🐟 Salmone', 'salmone', 'g', 'pesce'),
    ('🐟 Tonno fresco', 'tonno fresco', 'g', 'pesce'),
    ('🐟 Tonno in scatola', 'tonno in scatola', 'g', 'pesce'),
    ('🐟 Merluzzo', 'merluzzo', 'g', 'pesce'),
    ('🐟 Nasello', 'nasello', 'g', 'pesce'),
    ('🐟 Orata', 'orata', 'g', 'pesce'),
    ('🐟 Branzino', 'branzino', 'g', 'pesce'),
    ('🐟 Sogliola', 'sogliola', 'g', 'pesce'),
    ('🐟 Trota', 'trota', 'g', 'pesce'),
    ('🐟 Pesce spada', 'pesce spada', 'g', 'pesce'),
    ('🐟 Sgombro', 'sgombro', 'g', 'pesce'),
    ('🐟 Sardine', 'sardine', 'g', 'pesce'),
    ('🐟 Acciughe', 'acciughe', 'g', 'pesce'),
    ('🐟 Alici', 'alici', 'g', 'pesce'),
    ('🐟 Gamberi', 'gamberi', 'g', 'pesce'),
    ('🐟 Gamberetti', 'gamberetti', 'g', 'pesce'),
    ('🐟 Mazzancolle', 'mazzancolle', 'g', 'pesce'),
    ('🐟 Scampi', 'scampi', 'g', 'pesce'),
    ('🐟 Calamari', 'calamari', 'g', 'pesce'),
    ('🐟 Totani', 'totani', 'g', 'pesce'),
    ('🐟 Polpo', 'polpo', 'g', 'pesce'),
    ('🐟 Seppie', 'seppie', 'g', 'pesce'),
    ('🐟 Cozze', 'cozze', 'g', 'pesce'),
    ('🐟 Vongole', 'vongole', 'g', 'pesce'),
    ('🐟 Capasanta', 'capasanta', 'g', 'pesce'),
    ('🐟 Granchio', 'granchio', 'g', 'pesce'),
    ('🐟 Surimi', 'surimi', 'g', 'pesce'),
    ('🥛 Latte intero', 'latte intero', 'g', 'latticini'),
    ('🥛 Latte parzialmente scremato', 'latte parzialmente scremato', 'g', 'latticini'),
    ('🥛 Latte scremato', 'latte scremato', 'g', 'latticini'),
    ('🥛 Panna fresca', 'panna fresca', 'g', 'latticini'),
    ('🥛 Panna da cucina', 'panna da cucina', 'g', 'latticini'),
    ('🥛 Burro', 'burro', 'g', 'latticini'),
    ('🥛 Burro chiarificato', 'burro chiarificato', 'g', 'latticini'),
    ('🥛 Yogurt bianco', 'yogurt bianco', 'g', 'latticini'),
    ('🥛 Yogurt greco', 'yogurt greco', 'g', 'latticini'),
    ('🥛 Mascarpone', 'mascarpone', 'g', 'latticini'),
    ('🥛 Ricotta', 'ricotta', 'g', 'latticini'),
    ('🥛 Mozzarella', 'mozzarella', 'g', 'latticini'),
    ('🥛 Mozzarella di bufala', 'mozzarella di bufala', 'g', 'latticini'),
    ('🥛 Burrata', 'burrata', 'g', 'latticini'),
    ('🥛 Stracciatella', 'stracciatella', 'g', 'latticini'),
    ('🥛 Scamorza', 'scamorza', 'g', 'latticini'),
    ('🥛 Provola', 'provola', 'g', 'latticini'),
    ('🥛 Provolone', 'provolone', 'g', 'latticini'),
    ('🥛 Parmigiano Reggiano', 'parmigiano reggiano', 'g', 'latticini'),
    ('🥛 Grana Padano', 'grana padano', 'g', 'latticini'),
    ('🥛 Pecorino romano', 'pecorino romano', 'g', 'latticini'),
    ('🥛 Pecorino sardo', 'pecorino sardo', 'g', 'latticini'),
    ('🥛 Gorgonzola', 'gorgonzola', 'g', 'latticini'),
    ('🥛 Taleggio', 'taleggio', 'g', 'latticini'),
    ('🥛 Fontina', 'fontina', 'g', 'latticini'),
    ('🥛 Asiago', 'asiago', 'g', 'latticini'),
    ('🥛 Emmental', 'emmental', 'g', 'latticini'),
    ('🥛 Gruyère', 'gruyère', 'g', 'latticini'),
    ('🥛 Cheddar', 'cheddar', 'g', 'latticini'),
    ('🥛 Edam', 'edam', 'g', 'latticini'),
    ('🥛 Gouda', 'gouda', 'g', 'latticini'),
    ('🥛 Feta', 'feta', 'g', 'latticini'),
    ('🥛 Crescenza', 'crescenza', 'g', 'latticini'),
    ('🥛 Robiola', 'robiola', 'g', 'latticini'),
    ('🥛 Caprino', 'caprino', 'g', 'latticini'),
    ('🥛 Formaggio spalmabile', 'formaggio spalmabile', 'g', 'latticini'),
    ('🥚 Uova', 'uova', 'pz', 'uova'),
    ('🥚 Albumi', 'albumi', 'pz', 'uova'),
    ('🥚 Tuorli', 'tuorli', 'pz', 'uova'),
    ('🌾 Riso', 'riso', 'g', 'cereali'),
    ('🌾 Riso basmati', 'riso basmati', 'g', 'cereali'),
    ('🌾 Riso jasmine', 'riso jasmine', 'g', 'cereali'),
    ('🌾 Riso arborio', 'riso arborio', 'g', 'cereali'),
    ('🌾 Riso carnaroli', 'riso carnaroli', 'g', 'cereali'),
    ('🌾 Riso venere', 'riso venere', 'g', 'cereali'),
    ('🌾 Riso integrale', 'riso integrale', 'g', 'cereali'),
    ('🌾 Pasta', 'pasta', 'g', 'cereali'),
    ('🌾 Spaghetti', 'spaghetti', 'g', 'cereali'),
    ('🌾 Linguine', 'linguine', 'g', 'cereali'),
    ('🌾 Bucatini', 'bucatini', 'g', 'cereali'),
    ('🌾 Penne', 'penne', 'g', 'cereali'),
    ('🌾 Rigatoni', 'rigatoni', 'g', 'cereali'),
    ('🌾 Fusilli', 'fusilli', 'g', 'cereali'),
    ('🌾 Farfalle', 'farfalle', 'g', 'cereali'),
    ('🌾 Paccheri', 'paccheri', 'g', 'cereali'),
    ('🌾 Orecchiette', 'orecchiette', 'g', 'cereali'),
    ('🌾 Tagliatelle', 'tagliatelle', 'g', 'cereali'),
    ('🌾 Pappardelle', 'pappardelle', 'g', 'cereali'),
    ('🌾 Lasagne', 'lasagne', 'g', 'cereali'),
    ('🌾 Gnocchi di patate', 'gnocchi di patate', 'g', 'cereali'),
    ('🌾 Tortellini', 'tortellini', 'g', 'cereali'),
    ('🌾 Ravioli', 'ravioli', 'g', 'cereali'),
    ('🌾 Cous cous', 'cous cous', 'g', 'cereali'),
    ('🌾 Bulgur', 'bulgur', 'g', 'cereali'),
    ('🌾 Quinoa', 'quinoa', 'g', 'cereali'),
    ('🌾 Farro', 'farro', 'g', 'cereali'),
    ('🌾 Orzo perlato', 'orzo perlato', 'g', 'cereali'),
    ('🌾 Avena', 'avena', 'g', 'cereali'),
    ('🌾 Fiocchi di avena', 'fiocchi di avena', 'g', 'cereali'),
    ('🌾 Semolino', 'semolino', 'g', 'cereali'),
    ('🌾 Polenta', 'polenta', 'g', 'cereali'),
    ('🌾 Farina 00', 'farina 00', 'g', 'cereali'),
    ('🌾 Farina 0', 'farina 0', 'g', 'cereali'),
    ('🌾 Farina Manitoba', 'farina manitoba', 'g', 'cereali'),
    ('🌾 Farina integrale', 'farina integrale', 'g', 'cereali'),
    ('🌾 Farina di semola', 'farina di semola', 'g', 'cereali'),
    ('🌾 Farina di mais', 'farina di mais', 'g', 'cereali'),
    ('🌾 Farina di riso', 'farina di riso', 'g', 'cereali'),
    ('🌾 Farina di avena', 'farina di avena', 'g', 'cereali'),
    ('🌾 Farina di ceci', 'farina di ceci', 'g', 'cereali'),
    ('🌾 Amido di mais', 'amido di mais', 'g', 'cereali'),
    ('🌾 Fecola di patate', 'fecola di patate', 'g', 'cereali'),
    ('🌾 Pane', 'pane', 'g', 'cereali'),
    ('🌾 Pane bianco', 'pane bianco', 'g', 'cereali'),
    ('🌾 Pane integrale', 'pane integrale', 'g', 'cereali'),
    ('🌾 Pane in cassetta', 'pane in cassetta', 'g', 'cereali'),
    ('🌾 Pan brioche', 'pan brioche', 'g', 'cereali'),
    ('🌾 Baguette', 'baguette', 'g', 'cereali'),
    ('🌾 Ciabatta', 'ciabatta', 'g', 'cereali'),
    ('🌾 Piadina', 'piadina', 'g', 'cereali'),
    ('🌾 Tortilla di grano', 'tortilla di grano', 'g', 'cereali'),
    ('🌾 Tortilla di mais', 'tortilla di mais', 'g', 'cereali'),
    ('🌾 Pangrattato', 'pangrattato', 'g', 'cereali'),
    ('🌾 Cracker', 'cracker', 'g', 'cereali'),
    ('🌾 Grissini', 'grissini', 'g', 'cereali'),
    ('🌾 Fette biscottate', 'fette biscottate', 'g', 'cereali'),
    ('🌾 Corn flakes', 'corn flakes', 'g', 'cereali'),
    ('🫘 Fagioli borlotti', 'fagioli borlotti', 'g', 'legumi'),
    ('🫘 Fagioli cannellini', 'fagioli cannellini', 'g', 'legumi'),
    ('🫘 Fagioli neri', 'fagioli neri', 'g', 'legumi'),
    ('🫘 Fagioli rossi', 'fagioli rossi', 'g', 'legumi'),
    ('🫘 Fagioli azuki', 'fagioli azuki', 'g', 'legumi'),
    ('🫘 Ceci', 'ceci', 'g', 'legumi'),
    ('🫘 Lenticchie', 'lenticchie', 'g', 'legumi'),
    ('🫘 Lenticchie rosse', 'lenticchie rosse', 'g', 'legumi'),
    ('🫘 Piselli secchi', 'piselli secchi', 'g', 'legumi'),
    ('🫘 Fave secche', 'fave secche', 'g', 'legumi'),
    ('🫘 Soia', 'soia', 'g', 'legumi'),
    ('🫘 Edamame', 'edamame', 'g', 'legumi'),
    ('🫘 Tofu', 'tofu', 'g', 'legumi'),
    ('🫘 Tempeh', 'tempeh', 'g', 'legumi'),
    ('🧂 Sale fino', 'sale fino', 'g', 'condimenti'),
    ('🧂 Sale grosso', 'sale grosso', 'g', 'condimenti'),
    ('🧂 Pepe nero', 'pepe nero', 'g', 'condimenti'),
    ('🧂 Pepe bianco', 'pepe bianco', 'g', 'condimenti'),
    ('🧂 Pepe rosa', 'pepe rosa', 'g', 'condimenti'),
    ('🧂 Paprika dolce', 'paprika dolce', 'g', 'condimenti'),
    ('🧂 Paprika affumicata', 'paprika affumicata', 'g', 'condimenti'),
    ('🧂 Peperoncino', 'peperoncino', 'g', 'condimenti'),
    ('🧂 Curry', 'curry', 'g', 'condimenti'),
    ('🧂 Curcuma', 'curcuma', 'g', 'condimenti'),
    ('🧂 Cumino', 'cumino', 'g', 'condimenti'),
    ('🧂 Coriandolo in polvere', 'coriandolo in polvere', 'g', 'condimenti'),
    ('🧂 Cannella', 'cannella', 'g', 'condimenti'),
    ('🧂 Noce moscata', 'noce moscata', 'g', 'condimenti'),
    ('🧂 Zenzero in polvere', 'zenzero in polvere', 'g', 'condimenti'),
    ('🧂 Aglio in polvere', 'aglio in polvere', 'g', 'condimenti'),
    ('🧂 Cipolla in polvere', 'cipolla in polvere', 'g', 'condimenti'),
    ('🧂 Origano', 'origano', 'g', 'condimenti'),
    ('🧂 Basilico', 'basilico', 'g', 'condimenti'),
    ('🧂 Prezzemolo', 'prezzemolo', 'g', 'condimenti'),
    ('🧂 Rosmarino', 'rosmarino', 'g', 'condimenti'),
    ('🧂 Salvia', 'salvia', 'g', 'condimenti'),
    ('🧂 Timo', 'timo', 'g', 'condimenti'),
    ('🧂 Maggiorana', 'maggiorana', 'g', 'condimenti'),
    ('🧂 Erba cipollina', 'erba cipollina', 'g', 'condimenti'),
    ('🧂 Aneto', 'aneto', 'g', 'condimenti'),
    ('🧂 Menta', 'menta', 'g', 'condimenti'),
    ('🧂 Alloro', 'alloro', 'g', 'condimenti'),
    ('🧂 Semi di sesamo', 'semi di sesamo', 'g', 'condimenti'),
    ('🧂 Semi di papavero', 'semi di papavero', 'g', 'condimenti'),
    ('🧂 Semi di lino', 'semi di lino', 'g', 'condimenti'),
    ('🧂 Semi di chia', 'semi di chia', 'g', 'condimenti'),
    ('🧂 Semi di zucca', 'semi di zucca', 'g', 'condimenti'),
    ('🧂 Semi di girasole', 'semi di girasole', 'g', 'condimenti'),
    ('🧂 Pinoli', 'pinoli', 'g', 'condimenti'),
    ('🧂 Mandorle', 'mandorle', 'g', 'condimenti'),
    ('🧂 Nocciole', 'nocciole', 'g', 'condimenti'),
    ('🧂 Noci', 'noci', 'g', 'condimenti'),
    ('🧂 Pistacchi', 'pistacchi', 'g', 'condimenti'),
    ('🧂 Anacardi', 'anacardi', 'g', 'condimenti'),
    ('🧂 Arachidi', 'arachidi', 'g', 'condimenti'),
    ('🧂 Olio extravergine di oliva', 'olio extravergine di oliva', 'ml', 'condimenti'),
    ('🧂 Olio di oliva', 'olio di oliva', 'ml', 'condimenti'),
    ('🧂 Olio di semi di girasole', 'olio di semi di girasole', 'ml', 'condimenti'),
    ('🧂 Olio di arachidi', 'olio di arachidi', 'ml', 'condimenti'),
    ('🧂 Olio di mais', 'olio di mais', 'ml', 'condimenti'),
    ('🧂 Olio di sesamo', 'olio di sesamo', 'ml', 'condimenti'),
    ('🧂 Aceto di vino bianco', 'aceto di vino bianco', 'ml', 'condimenti'),
    ('🧂 Aceto di vino rosso', 'aceto di vino rosso', 'ml', 'condimenti'),
    ('🧂 Aceto balsamico', 'aceto balsamico', 'ml', 'condimenti'),
    ('🧂 Aceto di mele', 'aceto di mele', 'ml', 'condimenti'),
    ('🧂 Salsa di soia', 'salsa di soia', 'ml', 'condimenti'),
    ('🧂 Salsa teriyaki', 'salsa teriyaki', 'ml', 'condimenti'),
    ('🧂 Salsa Worcestershire', 'salsa worcestershire', 'ml', 'condimenti'),
    ('🧂 Ketchup', 'ketchup', 'ml', 'condimenti'),
    ('🧂 Maionese', 'maionese', 'ml', 'condimenti'),
    ('🧂 Senape', 'senape', 'ml', 'condimenti'),
    ('🧂 Senape di Digione', 'senape di digione', 'ml', 'condimenti'),
    ('🧂 Salsa barbecue', 'salsa barbecue', 'ml', 'condimenti'),
    ('🧂 Tabasco', 'tabasco', 'ml', 'condimenti'),
    ('🧂 Pesto', 'pesto', 'ml', 'condimenti'),
    ('🧂 Passata di pomodoro', 'passata di pomodoro', 'ml', 'condimenti'),
    ('🧂 Polpa di pomodoro', 'polpa di pomodoro', 'ml', 'condimenti'),
    ('🧂 Concentrato di pomodoro', 'concentrato di pomodoro', 'g', 'condimenti'),
    ('🧂 Pelati', 'pelati', 'g', 'condimenti'),
    ('🧂 Brodo vegetale', 'brodo vegetale', 'ml', 'condimenti'),
    ('🧂 Brodo di carne', 'brodo di carne', 'ml', 'condimenti'),
    ('🧂 Dado vegetale', 'dado vegetale', 'g', 'condimenti'),
    ('🧂 Dado di carne', 'dado di carne', 'g', 'condimenti'),
    ('🧂 Capperi', 'capperi', 'g', 'condimenti'),
    ('🧂 Cetriolini sottaceto', 'cetriolini sottaceto', 'g', 'condimenti'),
    ('🧂 Miele', 'miele', 'ml', 'condimenti'),
    ('🧂 Sciroppo d’acero', 'sciroppo d’acero', 'ml', 'condimenti'),
    ('🥤 Acqua', 'acqua', 'ml', 'bevande'),
    ('🥤 Acqua frizzante', 'acqua frizzante', 'ml', 'bevande'),
    ('🥤 Latte di soia', 'latte di soia', 'ml', 'bevande'),
    ('🥤 Latte di mandorla', 'latte di mandorla', 'ml', 'bevande'),
    ('🥤 Latte di avena', 'latte di avena', 'ml', 'bevande'),
    ('🥤 Latte di cocco', 'latte di cocco', 'ml', 'bevande'),
    ('🥤 Succo d’arancia', 'succo d’arancia', 'ml', 'bevande'),
    ('🥤 Succo di mela', 'succo di mela', 'ml', 'bevande'),
    ('🥤 Succo di ananas', 'succo di ananas', 'ml', 'bevande'),
    ('🥤 Succo di limone', 'succo di limone', 'ml', 'bevande'),
    ('🥤 Succo di lime', 'succo di lime', 'ml', 'bevande'),
    ('🥤 Caffè', 'caffè', 'ml', 'bevande'),
    ('🥤 Caffè espresso', 'caffè espresso', 'ml', 'bevande'),
    ('🥤 Caffè solubile', 'caffè solubile', 'ml', 'bevande'),
    ('🥤 Tè nero', 'tè nero', 'ml', 'bevande'),
    ('🥤 Tè verde', 'tè verde', 'ml', 'bevande'),
    ('🥤 Tè matcha', 'tè matcha', 'ml', 'bevande'),
    ('🥤 Camomilla', 'camomilla', 'ml', 'bevande'),
    ('🥤 Birra analcolica', 'birra analcolica', 'ml', 'bevande'),
    ('🥤 Acqua tonica', 'acqua tonica', 'ml', 'bevande'),
    ('🍰 Zucchero semolato', 'zucchero semolato', 'g', 'dolci'),
    ('🍰 Zucchero di canna', 'zucchero di canna', 'g', 'dolci'),
    ('🍰 Zucchero a velo', 'zucchero a velo', 'g', 'dolci'),
    ('🍰 Cacao amaro', 'cacao amaro', 'g', 'dolci'),
    ('🍰 Cacao zuccherato', 'cacao zuccherato', 'g', 'dolci'),
    ('🍰 Cioccolato fondente', 'cioccolato fondente', 'g', 'dolci'),
    ('🍰 Cioccolato al latte', 'cioccolato al latte', 'g', 'dolci'),
    ('🍰 Cioccolato bianco', 'cioccolato bianco', 'g', 'dolci'),
    ('🍰 Gocce di cioccolato', 'gocce di cioccolato', 'g', 'dolci'),
    ('🍰 Nutella', 'nutella', 'g', 'dolci'),
    ('🍰 Crema di nocciole', 'crema di nocciole', 'g', 'dolci'),
    ('🍰 Marmellata', 'marmellata', 'g', 'dolci'),
    ('🍰 Confettura', 'confettura', 'g', 'dolci'),
    ('🍰 Gelatina alimentare', 'gelatina alimentare', 'g', 'dolci'),
    ('🍰 Lievito per dolci', 'lievito per dolci', 'g', 'dolci'),
    ('🍰 Bicarbonato', 'bicarbonato', 'g', 'dolci'),
    ('🍰 Vanillina', 'vanillina', 'g', 'dolci'),
    ('🍰 Estratto di vaniglia', 'estratto di vaniglia', 'g', 'dolci'),
    ('🍰 Baccello di vaniglia', 'baccello di vaniglia', 'g', 'dolci'),
    ('🍰 Savoiardi', 'savoiardi', 'g', 'dolci'),
    ('🍰 Biscotti secchi', 'biscotti secchi', 'g', 'dolci'),
    ('🍰 Amaretti', 'amaretti', 'g', 'dolci'),
    ('🍰 Pan di Spagna', 'pan di spagna', 'g', 'dolci'),
    ('🍰 Marshmallow', 'marshmallow', 'g', 'dolci'),
    ('🍰 Caramello', 'caramello', 'g', 'dolci'),
    ('🍰 Codette di zucchero', 'codette di zucchero', 'g', 'dolci'),
    ('🏷️ Lievito di birra fresco', 'lievito di birra fresco', 'g', 'altro'),
    ('🏷️ Lievito di birra secco', 'lievito di birra secco', 'g', 'altro'),
    ('🏷️ Lievito madre', 'lievito madre', 'g', 'altro'),
    ('🏷️ Agar agar', 'agar agar', 'g', 'altro'),
    ('🏷️ Colla di pesce', 'colla di pesce', 'g', 'altro'),
    ('🏷️ Miso', 'miso', 'g', 'altro'),
    ('🏷️ Tahina', 'tahina', 'g', 'altro'),
    ('🏷️ Hummus', 'hummus', 'g', 'altro'),
    ('🏷️ Latte di cocco da cucina', 'latte di cocco da cucina', 'g', 'altro'),
    ('🏷️ Pasta sfoglia', 'pasta sfoglia', 'g', 'altro'),
    ('🏷️ Pasta brisée', 'pasta brisée', 'g', 'altro'),
    ('🏷️ Pasta fillo', 'pasta fillo', 'g', 'altro'),
    ('🏷️ Base per pizza', 'base per pizza', 'g', 'altro'),
    ('🏷️ Seitan', 'seitan', 'g', 'altro')
)
INSERT INTO alimento_categorie (alimento_id, categoria_id, assegnata_da_utente_id)
SELECT a.id, c.id, NULL
FROM seed
JOIN alimenti a
  ON a.catalogo_globale = 1
 AND a.nome_normalizzato = seed.nome_normalizzato
JOIN categorie_alimento c ON c.codice = seed.categoria_codice;
